### ISSUE TITLE
Mail-Notification Idea

### ISSUE THREAD

**Issue by BelaIbk** [SecondLiners/GO2#166]
Hey Gig-O-Matic Creator! Im a member of the SNO on Gig-o-matic and I had an idea to improve this wonderful Platform which is really usefull for our Band!
My idea was to add a Option where you cant regulary notify members who haven't opt in Ordnung Out at a certain Gig. 
This would be a good reminder for people to fill in their Status on important Gigs, No Matter if Kpositive or negative.
Hope you will think about my proposition and maybe eben give it a Go!
Greetings from Innsbruck,
Bela

P.S. i Hope im right Herr Wirth my message

**Comment by BelaIbk** [comment]
* I hope I'm right here with my message
German autocorrection (: ^^

**Comment by aaronoppenheimer** [comment]
Hi Bela - Do you mean, automatically email members who have not said whether they can be at a gig or not, as a reminder?

**Comment by BelaIbk** [comment]
Yeah that is exactly what I meant. It would be great to habe the possibility to activate and deactivate that option on specific Gigs tho. 
Thank you For responsing!
Am 10.10.2016 16:53 schrieb aaronoppenheimer <notifications@github.com>:

**Comment by aaronoppenheimer** [comment]
OK, I'll think about how best to do this. I have had others ask for this over the years!

**Comment by BelaIbk** [comment]
Thank you very much! This would really be a great function to be implemented!
Best regards!
Am 10.10.2016 17:39 schrieb aaronoppenheimer <notifications@github.com>:OK, I'll think about how best to do this. I have had others ask for this over the years!

**Comment by aaronoppenheimer** [comment]
Added "reminder" features.
