### ISSUE TITLE
Viewing "recently added members" on admin page would help multiple admins

### ISSUE THREAD

**Issue by kirkjerk** [SecondLiners/GO2#171]
If a group has multiple admins, each admin gets a "so and so is trying to join the group", but very often an admin clicks the link and finds nothing there because some other admin approved it... a "people added in last (1? 7?) days" list or other signal (like NEW! next to individual names on the list of members?) would help that

**Comment by aaronoppenheimer** [comment]
OK! Added a green star that shows up for a week when someone is new to the band.
