### ISSUE TITLE
form input fields not properly scrubbed

### ISSUE THREAD

**Issue by kirkjerk** [SecondLiners/GO2#173]
We had a gig called "The Commitments" Post-Gig Social Hour Movie Night
when I went to edit it, I couldn't submit right away because the title was blank... viewing source I see it went
<input type="text" class="form-control" id="gigtitleinput" placeholder="(required)" value=""The Commitments" Post-Gig Social Hour Movie Night" name="gig_title">
(Also makes me wonder if html tags etc are handled either... I know there are some security vulnerabilities that can come out of this stuff. Not that I'm TOO worried about nefarious cross-band sabotage, but you know :-) )

**Comment by aaronoppenheimer** [comment]
Fixed by adding the proper 'escape' to the template.
