### ISSUE TITLE
show name and nickname to admins

### ISSUE THREAD

**Issue by aaronoppenheimer** [SecondLiners/GO2#200]
Since we have both "name" and "nickname" find a way to show them both to admins, who complain that they don't know who's who by nickname. Right now, gig-o shows nickname if there is one, otherwise name. For admins, maybe use "name (nickname)" or something. Might mess up spacing in the display, though..?

**Comment by jackschmidt** [comment]
For desktop, maybe a title="{{the_member.name}}" (urlsafe?)

I think https://github.com/SecondLiners/GO2/blob/master/templates/grid.html#L90 becomes:

                            <a href="/member_info.html?mk={{member.urlsafe()}}"{% if the_member.nickname %} title="{{the_member.name}}">{{the_member.nickname}}{% else %}>{{ the_member.name }}{% endif %}</a>

I'd be happy with it for non-admins too :-)  Better solutions are welcome, but this might be a quick fix.
