### ISSUE TITLE
Forgot password email input is case sensitive, autocapitalized

### ISSUE THREAD

**Issue by kboedges** [SecondLiners/GO2#248]
When requesting to create a new password from forgot password from iPhone, the email address is auto-capitalized and then rejected because of the capital letter.

**Comment by aaronoppenheimer** [comment]
Hm. I wonder if there's something I can do to turn off the autocapitilization.

**Comment by kboedges** [comment]
I'm happy to work on this bug and submit a PR. I'm having a bit of trouble setting up the dev environment, though. Something about `pycrypto` not getting installed properly. I'll just do my testing through dev tools and xcode's simulator. 

I also saw when searching for errors about `pycryto` that it would be a good idea to change to `pycryptodome`. https://github.com/dlitz/pycrypto/issues/263

**Comment by kboedges** [comment]
@aaronoppenheimer I have a fix in a new branch. I'll open a PR if you give me access 🙂

**Comment by kboedges** [comment]
@aaronoppenheimer Not sure why, but I'm still getting this error when I try to push. 

`ERROR: Permission to SecondLiners/GO2.git denied to kboedges.`

**Comment by aaronoppenheimer** [comment]
Try now - I had added you to the organization but not made you a "collaborator." Weird that it's in a separate place (or it's just that I do this infrequently so don't know what I'm doing).

**Comment by aaronoppenheimer** [comment]
deployed!
